version: "3.1"

services:
  gitea:
    container_name: gitea
    image: gitea/gitea:latest
    restart: always
    ports:
      - 3000:3000
    volumes:
      - .data:/data/
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2G
        reservations:
          cpus: "0.5"
          memory: 200M

    healthcheck:
      test: netstat -anp | grep 3000
      interval: 45s
      timeout: 30s
      retries: 3
