version: "3.2"

services:
  httpd:
    container_name: httpd
    image: httpd:latest
    restart: "unless-stopped"
    ports:
      - 8800:80

    volumes:
      - ./files:/home/files/
      - ./conf:/usr/local/apache2/conf/
      - ./logs:/usr/local/apache2/logs/
      - ./htdocs:/usr/local/apache2/htdocs/

      # 时区
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

    deploy:
      resources:
        limits:
          cpus: "0.5" # 限制50%的CPU占用 
          memory: 1024M # 限制1024M内存占用 
