version: "3.1"

services:
  mariadb:
    container_name: mariadb
    image: mariadb:latest
    restart: always
    ports:
      - 3306:3306
    volumes:
      - .config:/etc/mysql/conf.d/
      - .data:/var/lib/mysql/
      - .log:/var/log/mysql/
    environment:
      MARIADB_ROOT_PASSWORD: zhuCong
    healthcheck:
      test: mysql --host=127.0.0.1 --user=root --password=$$MARIADB_ROOT_PASSWORD --silent --execute "SELECT 1;" || exit 1
      interval: 45s
      timeout: 30s
      retries: 3

  adminer:
    container_name: maraidb_adminer
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: mariadb
    healthcheck:
      test: curl -f http://localhost:8080/ || exit 1
      interval: 45s
      timeout: 30s
      retries: 3
