version: "3.2"

services:
  brook:
    container_name: brook
    image: teddysun/brook:latest
    restart: "unless-stopped"
    ports:
      - 1080:1080
      - 1081:1081

    volumes:
      # 时区
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

    environment:
      - ARGS=client --server 104.128.238.154:8629 --password 3KUBGShLqgg7NF
        --socks5 127.0.0.1:1080 --http 127.0.0.1:1081
    deploy:
      resources:
        limits:
          cpus: "0.5" # 限制50%的CPU占用 
          memory: 100M # 限制1024M内存占用 
