version: "3.1"

services:
  zentao:
    container_name: zentao
    image: easysoft/zentao:latest
    restart: "no"
    ports:
      - 8889:80
      - 3306:3306
    volumes:
      - .www:/www/zentaopms/
      - .data:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: zhuCong
